# the JOIN FUNCTION
# JOIN("${somelist}" ":" output)
function(JOIN VALUES GLUE OUTPUT)
  string (REGEX REPLACE "([^\\]|^);" "\\1${GLUE}" _TMP_STR "${VALUES}")
  set (${OUTPUT} "${_TMP_STR}" PARENT_SCOPE)
endfunction()

function(ADDTO_ENVPATH PATHSTRING)
	if (WIN32)
		message (STATUS "Win32")
		set (LD_VARNAME "PATH")
		JOIN("${PATHSTRING}" ";" LD_PATH)
		set (LD_PATH "$ENV{PATH};${LD_PATH}")
	elseif (APPLE)
		message (STATUS "Apple")
		set (LD_VARNAME "DYLD_LIBRARY_PATH")
		JOIN("${PATHSTRING}" ":" LD_PATH)
		set (LD_PATH "$ENV{DYLD_LIBRARY_PATH}:${LD_PATH}")
	elseif (UNIX)
		message (STATUS "Unix other than Apple")
		set (LD_VARNAME "LD_LIBRARY_PATH")
		JOIN("${PATHSTRING}" ":" LD_PATH)
		set (LD_PATH "$ENV{LD_LIBRARY_PATH}:${LD_PATH}")
	endif ()
endfunction ()