if (MSVC)
	add_definitions ( "/D${PROJECT_NAME_UPPER}_VERSION_MAJOR=${PROJECT_VERSION_MAJOR}" )
	add_definitions ( "/D${PROJECT_NAME_UPPER}_VERSION_MINOR=${PROJECT_VERSION_MINOR}" )
	add_definitions ( "/D${PROJECT_NAME_UPPER}_VERSION_${PROJECT_VERSION_MAJOR}_${PROJECT_VERSION_MINOR}" )
	add_definitions ( "/D_USE_MATH_DEFINES")
else ()
	add_definitions ( "-D${PROJECT_NAME_UPPER}_VERSION_MAJOR=${PROJECT_VERSION_MAJOR}" )
	add_definitions ( "-D${PROJECT_NAME_UPPER}_VERSION_MINOR=${PROJECT_VERSION_MINOR}" )
	add_definitions ( "-D${PROJECT_NAME_UPPER}_VERSION_${PROJECT_VERSION_MAJOR}_${PROJECT_VERSION_MINOR}" )
endif ()

if (${USE_MATLAB})
	if (MSVC)
		add_definitions ( "/DUSE_MATLAB" )
	else ()
		add_definitions ( "-DUSE_MATLAB" )
	endif ()
endif ()
