#ifndef PANORAMIX_CONFIG_CONFIG_HPP
#define PANORAMIX_CONFIG_CONFIG_HPP
 
#define PANORAMIX_VERSION_MAJOR @PROJECT_VERSION_MAJOR@
#define PANORAMIX_VERSION_MINOR @PROJECT_VERSION_MINOR@

#define PANORAMIX_VERSION_@PROJECT_VERSION_MAJOR@_@PROJECT_VERSION_MINOR@
 
#endif